### ISSUE TITLE
Update section on equal-bounds operator for 2.4+

### ISSUE THREAD

**Issue by dbaston** [postgis/postgis-workshops#1]
22.1.3 has some discussion of the equality operator that is no longer correct for newer versions of PostGIS:

> To allow for speedier comparison, the equal bounds operator, =, is provided. This operates only on the bounding box (rectangle), ensuring that the geometries occupy the same two dimensional extent, but not necessarily the same space.

**Comment by robe2** [comment]
It looks like this note was already changed to  :command:`~=` instead of `=` and so has the example.

So closing this out.  Not sure it's that much faster though than = which does an exact match.
