### ISSUE TITLE
Installation part of the workshop is not valid, OpenGeo doesn't exist anymore.

### ISSUE THREAD

**Issue by danielhamngren** [postgis/postgis-workshops#11]
The installation part of the workshop  (postgis-intro/sources/en/installation.rst (https://postgis.net/workshops/postgis-intro/installation.html)) is a guide on how to install the OpenGeo Suite which contain PostGIS. However OpenGeo doesn't exist anymore. 

I don't know if there is any other software suite which could be used as a drop in replacement for this workshop (I haven't finished it yet :)). Do you have any suggestion on approach?

**Comment by Ampretuzo** [comment]
I found the idea of running a graphical installer which happens to include postgis very off-putting - skipped that section and continued with a docker container from [this](https://github.com/postgis/docker-postgis) image supplemented with QGIS for visualization.
Installing postgis locally also extends pgadmin4 and enables it to display geometries in query results - quite handy for quick checks.

**Comment by robe2** [comment]
This has since been fixed.
