### ISSUE TITLE
Viewing data in QGIS

### ISSUE THREAD

**Issue by ruffyleaf** [postgis/postgis-workshops#18]
I've connected QGIS to Postgis, but the layers are not recognised.

Is there a step missing?

**Comment by Komzpa** [comment]
Hello @ruffyleaf, can you point exactly where you stopped and what you see?

**Comment by ruffyleaf** [comment]
Hi, ok, had cut and paste the bash script but I had to reformat that accordingly then the SQL files would be properly generated.

It works now.

Thank you!

**Comment by robe2** [comment]
Assume this is all set
