### ISSUE TITLE
Cannot find the  make.bat file

### ISSUE THREAD

**Issue by Auh3b** [postgis/postgis-workshops#20]
make html is failing to run

**Comment by robe2** [comment]
It uses Linux/Unix format.  So the file that Unix variants use is the Makefile.  That of course also assumes you have installed make. Using apt install make or pkg install make or some such thing.

Evidentially the person who wrote the Makefile must not use Windows.  If you want to take a stab at writing a script to work on windows, we'd welcome the contribution.

**Comment by robe2** [comment]
I'm going to close this out since no input.

One other option possibly is to use msys2 on windows.  That does understand Makefile if make is installed.

Admittedly I haven't bothered because the sphinx etc is a bigger dependency that I have no patience to install.

**Comment by pramsey** [comment]
Also, just in case a reminder: if you just want to read the content, it's online: https://postgis.net/workshops/postgis-intro/
