### ISSUE TITLE
No nyc_data.backup file in data bundle

### ISSUE THREAD

**Issue by vinnnyr** [postgis/postgis-workshops#25]
Hello, 

In section 5.1, Loading the Backup file: https://postgis.net/workshops/postgis-intro/loading_data.html#loading-the-backup-file

The tutorial says to restore from `nyc_data.backup`. This file does not seem to be in the data bundle link https://postgis.net/workshops/postgis-intro/index.html on the front page, nor does it seem like this file was generated in previous tutorials.

**Comment by pramsey** [comment]
Thanks, I've updated the data bundle to match the text now.
