### ISSUE TITLE
KNN section update

### ISSUE THREAD

**Issue by pramsey** [postgis/postgis-workshops#3]
The KNN section still thinks we're limited to bounding boxes. It also doesn't mention geography. Time for an update. http://postgis.net/workshops/postgis-intro/knn.html

**Comment by robe2** [comment]
Also need to get rid of mention of <#>

**Comment by robe2** [comment]
Looks like the limited to bounding boxes is gone, but still no mention of geography.

**Comment by pramsey** [comment]
I don't think I'm going to add that in. It's just an extra curlicue. I guess a one-sentence note or something "hey this also works for geography", but anything more would feel duplicative.
