### ISSUE TITLE
function not yet presented

### ISSUE THREAD

**Issue by jbarcelo3** [postgis/postgis-workshops#7]
https://postgis.net/workshops/postgis-intro/geometries_exercises.html****
To properly solve the third exercise, the student needs to use the ST_NumInteriorRings function; which has not yet been presented to them.
I presume that the intended course of action is that the student fails that particular question, so they later understand the importance of ST_NumInteriorRings. But proposing an exercise that the student cannot yet solve, is kind-of dishonest from the instructor. More so if the exercise is proposed with no warning about that circumstance.

**Comment by robe2** [comment]
The 3rd exercise now is 

What is the GeoJSON representation of the ‘Broad St’ subway station?
```

SELECT
 ST_AsGeoJSON(geom)
FROM nyc_subway_stations
WHERE name = 'Broad St';
```

I presume this issue was raised earlier when perhaps there was something that involved ST_NumInteriorRings and is no longer relevant.
