### ISSUE TITLE
terminology

### ISSUE THREAD

**Issue by mattdstep** [postgis/postgis-workshops#74]
Hello,

I am new to postgres and am trying to walk through your postGIS tutorial. On the 5. Loading Spatial Data page I got lost on 5.2 with the instruction to be in the 2000 sub-directory within the shell. I am familiar with the concept here, but not where to actually find the shell within PGAdmin4. This could just be an issue for me because I am not familiar enough with postgres or PGAdmin to complete this tutorial, but I can't confirm that because I don't see a statement of necessary background information at the beginning of the tutorial.

Best,

Matt

**Comment by pramsey** [comment]
If you completed section 5.1 you have the data loaded and you can continue on. The following sections are alternative ways to load data, which depend on some comfort with running programs on the command line. If this "does not compute" then just skip ahead to 6. @robe2 maybe a note at 5.2 that the following sections are command-line *alternatives* to the preceding restore.

**Comment by mattdstep** [comment]
Got it, I was able to continue. Thank you!
