### ISSUE TITLE
What is happening to postgis.net ?

### ISSUE THREAD

**Issue by yw662** [postgis/postgis-workshops#76]
I tried `http://postgis.net` and `https://postgis.net` but the only response I get is connect reset by peer. What is happening and is there any mirror of the site ?

**Comment by robe2** [comment]
I'm not seeing an issue here, are you still having issues.  I think there was a brief outage yesterday - at least my monitor did go off for about 5 minutes.

**Comment by yw662** [comment]
It works now. For me it is about an hour yesterday.
