### ISSUE TITLE
Loading data - shapefiles

### ISSUE THREAD

**Issue by Craicerjack** [postgis/postgis-workshops#8]
https://postgis.net/workshops/postgis-intro/loading_data.html  

### 5. Loading spatial data  

This section is outdated? 
Running postgresql 10 and pgadmin4 I dont have an **Import shapefiles link** nor a **PostGIS** section  

It seems opengeo suite was bought by someone else so I was unable to use it and the packages that it installed werent available.

**Comment by pramsey** [comment]
Many sections are aged, contributions welcome!

**Comment by Craicerjack** [comment]
If I figure it out I'll get back to you.

**Comment by Craicerjack** [comment]
Okay so this is how I ended up getting the loader working

Ubuntu 18.04
Postgresql 10  
postgis 2.5  
pgadmin3 (written in php?) pgamdin4 seems to be python so havent figured out how to apply it to that yet.  

to install the shapeloader  
`sudo apt install postgis-gui`  
`sudo vim /usr/share/pgadmin3/plugins.d/plugins.ini`  
then add this to the end of plugins.ini

```
;
; pgShapeLoader (Linux):
;
Title=PostGIS Shapefile and DBF loader
Command=/usr/bin/shp2pgsql-gui -U $$USERNAME -d $$DATABASE -p $$PORT -h $$HOSTNAME
Description=Open a PostGIS ESRI Shapefile or Plain dbf loader console to the current database.
KeyFile=/usr/bin/shp2pgsql-gui
Platform=unix
ServerType=postgresql
Database=Yes
SetPassword=No
```  

Then in the plugins section I was able to open the uploader
